version: '3'

volumes:
  foodgarm_pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - foodgarm_pg_data:/var/lib/postgresql/data
  

  backend:
    image: lgaben/foodgarm_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: lgaben/foodgarm_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/ 
    volumes:
      - static:/frontend_static 
  
  nginx:
    image: lgaben/foodgarm_gateway:latest
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media